#!/bin/bash
# Baixa fontes livres (licença OFL / Apache) do repositório oficial github.com/google/fonts para a pasta fontes/.
# Uso: bash baixar_fontes.sh        (já baixadas são puladas)
cd "$(dirname "$0")" && mkdir -p fontes && cd fontes
R="https://raw.githubusercontent.com/google/fonts/main"
LISTA="
ofl/lobster/Lobster-Regular
ofl/lobstertwo/LobsterTwo-Bold
ofl/pacifico/Pacifico-Regular
apache/chewy/Chewy-Regular
apache/luckiestguy/LuckiestGuy-Regular
ofl/modak/Modak-Regular
ofl/titanone/TitanOne-Regular
ofl/mousememoirs/MouseMemoirs-Regular
ofl/sigmarone/SigmarOne-Regular
ofl/bubblegumsans/BubblegumSans-Regular
ofl/pixelifysans/PixelifySans%5Bwght%5D
ofl/silkscreen/Silkscreen-Bold
ofl/pressstart2p/PressStart2P-Regular
ofl/vt323/VT323-Regular
ofl/jersey10/Jersey10-Regular
ofl/tiny5/Tiny5-Regular
ofl/micro5/Micro5-Regular
ofl/pirataone/PirataOne-Regular
ofl/jollylodger/JollyLodger-Regular
ofl/newrocker/NewRocker-Regular
ofl/sancreek/Sancreek-Regular
ofl/rye/Rye-Regular
ofl/ribeye/Ribeye-Regular
ofl/notoemoji/NotoEmoji%5Bwght%5D
ofl/notosanssymbols2/NotoSansSymbols2-Regular
ofl/courgette/Courgette-Regular
ofl/damion/Damion-Regular
ofl/satisfy/Satisfy-Regular
ofl/playball/Playball-Regular
ofl/emilyscandy/EmilysCandy-Regular
ofl/lilyscriptone/LilyScriptOne-Regular
ofl/dancingscript/DancingScript%5Bwght%5D
ofl/sacramento/Sacramento-Regular
ofl/greatvibes/GreatVibes-Regular
ofl/permanentmarker/PermanentMarker-Regular
apache/permanentmarker/PermanentMarker-Regular
ofl/knewave/Knewave-Regular
ofl/sriracha/Sriracha-Regular
ofl/yesteryear/Yesteryear-Regular
ofl/parisienne/Parisienne-Regular
ofl/allura/Allura-Regular
ofl/alexbrush/AlexBrush-Regular
ofl/badscript/BadScript-Regular
ofl/marckscript/MarckScript-Regular
ofl/norican/Norican-Regular
ofl/oleoscript/OleoScript-Bold
ofl/pattaya/Pattaya-Regular
ofl/rochester/Rochester-Regular
ofl/sofia/Sofia-Regular
ofl/niconne/Niconne-Regular
ofl/kalam/Kalam-Bold
ofl/patrickhand/PatrickHand-Regular
ofl/shadowsintolight/ShadowsIntoLight-Regular
ofl/amaticsc/AmaticSC-Bold
ofl/handlee/Handlee-Regular
ofl/gloriahallelujah/GloriaHallelujah-Regular
ofl/frederickathegreat/FrederickaTheGreat-Regular
ofl/lemon/Lemon-Regular
ofl/mogra/Mogra-Regular
ofl/spicyrice/SpicyRice-Regular
ofl/sonsieone/SonsieOne-Regular
ofl/coiny/Coiny-Regular
ofl/chicle/Chicle-Regular
ofl/galindo/Galindo-Regular
ofl/gorditas/Gorditas-Bold
ofl/jua/Jua-Regular
ofl/kavoon/Kavoon-Regular
ofl/londrinasolid/LondrinaSolid-Black
ofl/varelaround/VarelaRound-Regular
ofl/boogaloo/Boogaloo-Regular
ofl/bevan/Bevan-Regular
ofl/righteous/Righteous-Regular
ofl/fugazone/FugazOne-Regular
ofl/concertone/ConcertOne-Regular
ofl/bungee/Bungee-Regular
ofl/rammettoone/RammettoOne-Regular
ofl/slackey/Slackey-Regular
ofl/mochiypopone/MochiyPopOne-Regular
ofl/dotgothic16/DotGothic16-Regular
ofl/jacquard24/Jacquard24-Regular
ofl/handjet/Handjet%5BELGR%2CELSH%2Cwght%5D
ofl/medievalsharp/MedievalSharp-Regular
ofl/almendra/Almendra-Bold
ofl/uncialantiqua/UncialAntiqua-Regular
ofl/metamorphous/Metamorphous-Regular
ofl/creepster/Creepster-Regular
ofl/smokum/Smokum-Regular
ofl/ewert/Ewert-Regular
ofl/holtwoodonesc/HoltwoodOneSC-Regular
ofl/vastshadow/VastShadow-Regular
ofl/wellfleet/Wellfleet-Regular
ofl/eater/Eater-Regular
ofl/lovers quarrel/LoversQuarrel-Regular
ofl/loversquarrel/LoversQuarrel-Regular
ofl/arimo/static/Arimo-Bold
ofl/tinos/Tinos-Bold
ofl/cousine/Cousine-Bold
ofl/opensans/static/OpenSans-ExtraBold
ofl/carterone/CarterOne
ofl/fredokaone/FredokaOne
"
for f in $LISTA; do
  n=$(basename "$f" | sed 's/%5B.*//')
  if [ -s "$n.ttf" ]; then continue; fi
  code=$(curl -s -L -o "$n.ttf" -w "%{http_code}" "$R/$f.ttf")
  sz=$(stat -c %s "$n.ttf" 2>/dev/null)
  if [ "$code" != "200" ] || [ "${sz:-0}" -lt 5000 ]; then rm -f "$n.ttf"; echo "FALHOU $f ($code)"; else echo "ok $n.ttf $sz"; fi
done
